### PR TITLE
ENH: Push docker image to dockerhub

### PR DESCRIPTION
**Pull request by fdumais**
Add docker push inside build_docker_image.yml to always push the newly build docker image

### CODE REVIEW

**Review by jhlegarreta — COMMENTED** [review]
I think pushing to dockerhub should be a separate workflow file: we should only push to dockerhub when we tag/release a version (and the workflow ideally could be triggered automatically when doing that), otherwise we will be pushing a version for every change (i.e. every commit, even when a commit adds a comment to the build file or the `README`).

Maybe we can use this as a test, open a new PR that adds a workflow file where the action is triggered only when tagging/releasing a version, then transferring the content in here to that PR/workflow file.

**Comment by jhlegarreta** [comment]
Also, I'm sure there is a way to create a badge for the `README` that points to the image in dockerhub. Adding that and a link in the `README` and/or the project properties.

**Comment by jhlegarreta** [comment]
Looks like triggering the action on a release event is not difficult:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release

We may want to experience on a testing repository with some other workflow in a test repository to make sure that we master the action/understand how it works.

**Comment by felixdumais** [comment]
> I think pushing to dockerhub should be a separate workflow file: we should only push to dockerhub when we tag/release a version (and the workflow ideally could be triggered automatically when doing that), otherwise we will be pushing a version for every change (i.e. every commit, even when a commit adds a comment to the build file or the `README`).
> 
> Maybe we can use this as a test, open a new PR that adds a workflow file where the action is triggered only when tagging/releasing a version, then transferring the content in here to that PR/workflow file.

Ok, but I would like to always have a latest version. So I suggest we push a version latest every time. We should do a tag push github workflow in the repo tractolearn.

**Comment by felixdumais** [comment]
> Also, I'm sure there is a way to create a badge for the `README` that points to the image in dockerhub. Adding that and a link in the `README` and/or the project properties.

Done

**Comment by fdumais** [comment]
@jhlegarreta Ok if I merge ? For the tag action we may want to do it in the tractolearn repo. For now I would prefer if we always push a latest version

**Review by jhlegarreta — APPROVED** [review]

**Comment by jhlegarreta** [comment]
> @jhlegarreta Ok if I merge ? For the tag action we may want to do it in the tractolearn repo. For now I would prefer if we always push a latest version

I'm merging. If possible, we should leave to another maintainer merging a PR of one's own.

**Comment by jhlegarreta** [comment]
~I'm merging.~

I do not have merge rights on this repository.

**Comment by jhlegarreta** [comment]
@fdumais it dawned on me whether by pushing a new image per commit, we will exceed the available space (if any) on the corresponding Dockerhub account.

**Pull request merged**
